spring:
  application:
    name: bus-gateway

server:
  port: 2333

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/

zuul:
  routes:
    demo-api-a:
      serviceId: demo-api-a
      path: /**
    demo-api-b:
      serviceId: demo-api-b
      path: /**

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000