spring:
  application:
    name: bus-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liumapp/spring-cloud-bus-demo/
          search-paths: config

server:
  port: 7001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/

