spring:
  application:
    name: demo-api-b
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: your_eureka_serviceId
      profile: dev
      label: master
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1234/eureka/